export interface Country {
    code: string
    name: string
    dialCode: string
    flag: string
}

export const countries: Country[] = [
    { code: "AF", name: "Afghanistan", dialCode: "+93", flag: "https://flagcdn.com/w40/af.png" },
    { code: "AL", name: "Albania", dialCode: "+355", flag: "https://flagcdn.com/w40/al.png" },
    { code: "DZ", name: "Algeria", dialCode: "+213", flag: "https://flagcdn.com/w40/dz.png" },
    { code: "AS", name: "American Samoa", dialCode: "+1684", flag: "https://flagcdn.com/w40/as.png" },
    { code: "AD", name: "Andorra", dialCode: "+376", flag: "https://flagcdn.com/w40/ad.png" },
    { code: "AO", name: "Angola", dialCode: "+244", flag: "https://flagcdn.com/w40/ao.png" },
    { code: "AI", name: "Anguilla", dialCode: "+1264", flag: "https://flagcdn.com/w40/ai.png" },
    { code: "AG", name: "Antigua and Barbuda", dialCode: "+1268", flag: "https://flagcdn.com/w40/ag.png" },
    { code: "AR", name: "Argentina", dialCode: "+54", flag: "https://flagcdn.com/w40/ar.png" },
    { code: "AM", name: "Armenia", dialCode: "+374", flag: "https://flagcdn.com/w40/am.png" },
    { code: "AW", name: "Aruba", dialCode: "+297", flag: "https://flagcdn.com/w40/aw.png" },
    { code: "AU", name: "Australia", dialCode: "+61", flag: "https://flagcdn.com/w40/au.png" },
    { code: "AT", name: "Austria", dialCode: "+43", flag: "https://flagcdn.com/w40/at.png" },
    { code: "AZ", name: "Azerbaijan", dialCode: "+994", flag: "https://flagcdn.com/w40/az.png" },
    { code: "BS", name: "Bahamas", dialCode: "+1242", flag: "https://flagcdn.com/w40/bs.png" },
    { code: "BH", name: "Bahrain", dialCode: "+973", flag: "https://flagcdn.com/w40/bh.png" },
    { code: "BD", name: "Bangladesh", dialCode: "+880", flag: "https://flagcdn.com/w40/bd.png" },
    { code: "BB", name: "Barbados", dialCode: "+1246", flag: "https://flagcdn.com/w40/bb.png" },
    { code: "BY", name: "Belarus", dialCode: "+375", flag: "https://flagcdn.com/w40/by.png" },
    { code: "BE", name: "Belgium", dialCode: "+32", flag: "https://flagcdn.com/w40/be.png" },
    { code: "BZ", name: "Belize", dialCode: "+501", flag: "https://flagcdn.com/w40/bz.png" },
    { code: "BJ", name: "Benin", dialCode: "+229", flag: "https://flagcdn.com/w40/bj.png" },
    { code: "BM", name: "Bermuda", dialCode: "+1441", flag: "https://flagcdn.com/w40/bm.png" },
    { code: "BT", name: "Bhutan", dialCode: "+975", flag: "https://flagcdn.com/w40/bt.png" },
    { code: "BO", name: "Bolivia", dialCode: "+591", flag: "https://flagcdn.com/w40/bo.png" },
    { code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", flag: "https://flagcdn.com/w40/ba.png" },
    { code: "BW", name: "Botswana", dialCode: "+267", flag: "https://flagcdn.com/w40/bw.png" },
    { code: "BR", name: "Brazil", dialCode: "+55", flag: "https://flagcdn.com/w40/br.png" },
    { code: "BN", name: "Brunei", dialCode: "+673", flag: "https://flagcdn.com/w40/bn.png" },
    { code: "BG", name: "Bulgaria", dialCode: "+359", flag: "https://flagcdn.com/w40/bg.png" },
    { code: "BF", name: "Burkina Faso", dialCode: "+226", flag: "https://flagcdn.com/w40/bf.png" },
    { code: "BI", name: "Burundi", dialCode: "+257", flag: "https://flagcdn.com/w40/bi.png" },
    { code: "KH", name: "Cambodia", dialCode: "+855", flag: "https://flagcdn.com/w40/kh.png" },
    { code: "CM", name: "Cameroon", dialCode: "+237", flag: "https://flagcdn.com/w40/cm.png" },
    { code: "CA", name: "Canada", dialCode: "+1", flag: "https://flagcdn.com/w40/ca.png" },
    { code: "CV", name: "Cape Verde", dialCode: "+238", flag: "https://flagcdn.com/w40/cv.png" },
    { code: "KY", name: "Cayman Islands", dialCode: "+1345", flag: "https://flagcdn.com/w40/ky.png" },
    { code: "CF", name: "Central African Republic", dialCode: "+236", flag: "https://flagcdn.com/w40/cf.png" },
    { code: "TD", name: "Chad", dialCode: "+235", flag: "https://flagcdn.com/w40/td.png" },
    { code: "CL", name: "Chile", dialCode: "+56", flag: "https://flagcdn.com/w40/cl.png" },
    { code: "CN", name: "China", dialCode: "+86", flag: "https://flagcdn.com/w40/cn.png" },
    { code: "CO", name: "Colombia", dialCode: "+57", flag: "https://flagcdn.com/w40/co.png" },
    { code: "KM", name: "Comoros", dialCode: "+269", flag: "https://flagcdn.com/w40/km.png" },
    { code: "CG", name: "Congo", dialCode: "+242", flag: "https://flagcdn.com/w40/cg.png" },
    { code: "CD", name: "Congo (DRC)", dialCode: "+243", flag: "https://flagcdn.com/w40/cd.png" },
    { code: "CK", name: "Cook Islands", dialCode: "+682", flag: "https://flagcdn.com/w40/ck.png" },
    { code: "CR", name: "Costa Rica", dialCode: "+506", flag: "https://flagcdn.com/w40/cr.png" },
    { code: "CI", name: "Côte d'Ivoire", dialCode: "+225", flag: "https://flagcdn.com/w40/ci.png" },
    { code: "HR", name: "Croatia", dialCode: "+385", flag: "https://flagcdn.com/w40/hr.png" },
    { code: "CU", name: "Cuba", dialCode: "+53", flag: "https://flagcdn.com/w40/cu.png" },
    { code: "CY", name: "Cyprus", dialCode: "+357", flag: "https://flagcdn.com/w40/cy.png" },
    { code: "CZ", name: "Czech Republic", dialCode: "+420", flag: "https://flagcdn.com/w40/cz.png" },
    { code: "DK", name: "Denmark", dialCode: "+45", flag: "https://flagcdn.com/w40/dk.png" },
    { code: "DJ", name: "Djibouti", dialCode: "+253", flag: "https://flagcdn.com/w40/dj.png" },
    { code: "DM", name: "Dominica", dialCode: "+1767", flag: "https://flagcdn.com/w40/dm.png" },
    { code: "DO", name: "Dominican Republic", dialCode: "+1", flag: "https://flagcdn.com/w40/do.png" },
    { code: "EC", name: "Ecuador", dialCode: "+593", flag: "https://flagcdn.com/w40/ec.png" },
    { code: "EG", name: "Egypt", dialCode: "+20", flag: "https://flagcdn.com/w40/eg.png" },
    { code: "SV", name: "El Salvador", dialCode: "+503", flag: "https://flagcdn.com/w40/sv.png" },
    { code: "GQ", name: "Equatorial Guinea", dialCode: "+240", flag: "https://flagcdn.com/w40/gq.png" },
    { code: "ER", name: "Eritrea", dialCode: "+291", flag: "https://flagcdn.com/w40/er.png" },
    { code: "EE", name: "Estonia", dialCode: "+372", flag: "https://flagcdn.com/w40/ee.png" },
    { code: "ET", name: "Ethiopia", dialCode: "+251", flag: "https://flagcdn.com/w40/et.png" },
    { code: "FJ", name: "Fiji", dialCode: "+679", flag: "https://flagcdn.com/w40/fj.png" },
    { code: "FI", name: "Finland", dialCode: "+358", flag: "https://flagcdn.com/w40/fi.png" },
    { code: "FR", name: "France", dialCode: "+33", flag: "https://flagcdn.com/w40/fr.png" },
    { code: "GA", name: "Gabon", dialCode: "+241", flag: "https://flagcdn.com/w40/ga.png" },
    { code: "GM", name: "Gambia", dialCode: "+220", flag: "https://flagcdn.com/w40/gm.png" },
    { code: "GE", name: "Georgia", dialCode: "+995", flag: "https://flagcdn.com/w40/ge.png" },
    { code: "DE", name: "Germany", dialCode: "+49", flag: "https://flagcdn.com/w40/de.png" },
    { code: "GH", name: "Ghana", dialCode: "+233", flag: "https://flagcdn.com/w40/gh.png" },
    { code: "GR", name: "Greece", dialCode: "+30", flag: "https://flagcdn.com/w40/gr.png" },
    { code: "GD", name: "Grenada", dialCode: "+1473", flag: "https://flagcdn.com/w40/gd.png" },
    { code: "GT", name: "Guatemala", dialCode: "+502", flag: "https://flagcdn.com/w40/gt.png" },
    { code: "GN", name: "Guinea", dialCode: "+224", flag: "https://flagcdn.com/w40/gn.png" },
    { code: "GW", name: "Guinea-Bissau", dialCode: "+245", flag: "https://flagcdn.com/w40/gw.png" },
    { code: "GY", name: "Guyana", dialCode: "+592", flag: "https://flagcdn.com/w40/gy.png" },
    { code: "HT", name: "Haiti", dialCode: "+509", flag: "https://flagcdn.com/w40/ht.png" },
    { code: "HN", name: "Honduras", dialCode: "+504", flag: "https://flagcdn.com/w40/hn.png" },
    { code: "HK", name: "Hong Kong", dialCode: "+852", flag: "https://flagcdn.com/w40/hk.png" },
    { code: "HU", name: "Hungary", dialCode: "+36", flag: "https://flagcdn.com/w40/hu.png" },
    { code: "IS", name: "Iceland", dialCode: "+354", flag: "https://flagcdn.com/w40/is.png" },
    { code: "IN", name: "India", dialCode: "+91", flag: "https://flagcdn.com/w40/in.png" },
    { code: "ID", name: "Indonesia", dialCode: "+62", flag: "https://flagcdn.com/w40/id.png" },
    { code: "IR", name: "Iran", dialCode: "+98", flag: "https://flagcdn.com/w40/ir.png" },
    { code: "IQ", name: "Iraq", dialCode: "+964", flag: "https://flagcdn.com/w40/iq.png" },
    { code: "IE", name: "Ireland", dialCode: "+353", flag: "https://flagcdn.com/w40/ie.png" },
    { code: "IL", name: "Israel", dialCode: "+972", flag: "https://flagcdn.com/w40/il.png" },
    { code: "IT", name: "Italy", dialCode: "+39", flag: "https://flagcdn.com/w40/it.png" },
    { code: "JM", name: "Jamaica", dialCode: "+1876", flag: "https://flagcdn.com/w40/jm.png" },
    { code: "JP", name: "Japan", dialCode: "+81", flag: "https://flagcdn.com/w40/jp.png" },
    { code: "JO", name: "Jordan", dialCode: "+962", flag: "https://flagcdn.com/w40/jo.png" },
    { code: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "https://flagcdn.com/w40/kz.png" },
    { code: "KE", name: "Kenya", dialCode: "+254", flag: "https://flagcdn.com/w40/ke.png" },
    { code: "KI", name: "Kiribati", dialCode: "+686", flag: "https://flagcdn.com/w40/ki.png" },
    { code: "KP", name: "North Korea", dialCode: "+850", flag: "https://flagcdn.com/w40/kp.png" },
    { code: "KR", name: "South Korea", dialCode: "+82", flag: "https://flagcdn.com/w40/kr.png" },
    { code: "KW", name: "Kuwait", dialCode: "+965", flag: "https://flagcdn.com/w40/kw.png" },
    { code: "KG", name: "Kyrgyzstan", dialCode: "+996", flag: "https://flagcdn.com/w40/kg.png" },
    { code: "LA", name: "Laos", dialCode: "+856", flag: "https://flagcdn.com/w40/la.png" },
    { code: "LV", name: "Latvia", dialCode: "+371", flag: "https://flagcdn.com/w40/lv.png" },
    { code: "LB", name: "Lebanon", dialCode: "+961", flag: "https://flagcdn.com/w40/lb.png" },
    { code: "LS", name: "Lesotho", dialCode: "+266", flag: "https://flagcdn.com/w40/ls.png" },
    { code: "LR", name: "Liberia", dialCode: "+231", flag: "https://flagcdn.com/w40/lr.png" },
    { code: "LY", name: "Libya", dialCode: "+218", flag: "https://flagcdn.com/w40/ly.png" },
    { code: "LI", name: "Liechtenstein", dialCode: "+423", flag: "https://flagcdn.com/w40/li.png" },
    { code: "LT", name: "Lithuania", dialCode: "+370", flag: "https://flagcdn.com/w40/lt.png" },
    { code: "LU", name: "Luxembourg", dialCode: "+352", flag: "https://flagcdn.com/w40/lu.png" },
    { code: "MO", name: "Macao", dialCode: "+853", flag: "https://flagcdn.com/w40/mo.png" },
    { code: "MK", name: "North Macedonia", dialCode: "+389", flag: "https://flagcdn.com/w40/mk.png" },
    { code: "MG", name: "Madagascar", dialCode: "+261", flag: "https://flagcdn.com/w40/mg.png" },
    { code: "MW", name: "Malawi", dialCode: "+265", flag: "https://flagcdn.com/w40/mw.png" },
    { code: "MY", name: "Malaysia", dialCode: "+60", flag: "https://flagcdn.com/w40/my.png" },
    { code: "MV", name: "Maldives", dialCode: "+960", flag: "https://flagcdn.com/w40/mv.png" },
    { code: "ML", name: "Mali", dialCode: "+223", flag: "https://flagcdn.com/w40/ml.png" },
    { code: "MT", name: "Malta", dialCode: "+356", flag: "https://flagcdn.com/w40/mt.png" },
    { code: "MH", name: "Marshall Islands", dialCode: "+692", flag: "https://flagcdn.com/w40/mh.png" },
    { code: "MR", name: "Mauritania", dialCode: "+222", flag: "https://flagcdn.com/w40/mr.png" },
    { code: "MU", name: "Mauritius", dialCode: "+230", flag: "https://flagcdn.com/w40/mu.png" },
    { code: "MX", name: "Mexico", dialCode: "+52", flag: "https://flagcdn.com/w40/mx.png" },
    { code: "FM", name: "Micronesia", dialCode: "+691", flag: "https://flagcdn.com/w40/fm.png" },
    { code: "MD", name: "Moldova", dialCode: "+373", flag: "https://flagcdn.com/w40/md.png" },
    { code: "MC", name: "Monaco", dialCode: "+377", flag: "https://flagcdn.com/w40/mc.png" },
    { code: "MN", name: "Mongolia", dialCode: "+976", flag: "https://flagcdn.com/w40/mn.png" },
    { code: "ME", name: "Montenegro", dialCode: "+382", flag: "https://flagcdn.com/w40/me.png" },
    { code: "MA", name: "Morocco", dialCode: "+212", flag: "https://flagcdn.com/w40/ma.png" },
    { code: "MZ", name: "Mozambique", dialCode: "+258", flag: "https://flagcdn.com/w40/mz.png" },
    { code: "MM", name: "Myanmar", dialCode: "+95", flag: "https://flagcdn.com/w40/mm.png" },
    { code: "NA", name: "Namibia", dialCode: "+264", flag: "https://flagcdn.com/w40/na.png" },
    { code: "NR", name: "Nauru", dialCode: "+674", flag: "https://flagcdn.com/w40/nr.png" },
    { code: "NP", name: "Nepal", dialCode: "+977", flag: "https://flagcdn.com/w40/np.png" },
    { code: "NL", name: "Netherlands", dialCode: "+31", flag: "https://flagcdn.com/w40/nl.png" },
    { code: "NZ", name: "New Zealand", dialCode: "+64", flag: "https://flagcdn.com/w40/nz.png" },
    { code: "NI", name: "Nicaragua", dialCode: "+505", flag: "https://flagcdn.com/w40/ni.png" },
    { code: "NE", name: "Niger", dialCode: "+227", flag: "https://flagcdn.com/w40/ne.png" },
    { code: "NG", name: "Nigeria", dialCode: "+234", flag: "https://flagcdn.com/w40/ng.png" },
    { code: "NO", name: "Norway", dialCode: "+47", flag: "https://flagcdn.com/w40/no.png" },
    { code: "OM", name: "Oman", dialCode: "+968", flag: "https://flagcdn.com/w40/om.png" },
    { code: "PK", name: "Pakistan", dialCode: "+92", flag: "https://flagcdn.com/w40/pk.png" },
    { code: "PW", name: "Palau", dialCode: "+680", flag: "https://flagcdn.com/w40/pw.png" },
    { code: "PS", name: "Palestine", dialCode: "+970", flag: "https://flagcdn.com/w40/ps.png" },
    { code: "PA", name: "Panama", dialCode: "+507", flag: "https://flagcdn.com/w40/pa.png" },
    { code: "PG", name: "Papua New Guinea", dialCode: "+675", flag: "https://flagcdn.com/w40/pg.png" },
    { code: "PY", name: "Paraguay", dialCode: "+595", flag: "https://flagcdn.com/w40/py.png" },
    { code: "PE", name: "Peru", dialCode: "+51", flag: "https://flagcdn.com/w40/pe.png" },
    { code: "PH", name: "Philippines", dialCode: "+63", flag: "https://flagcdn.com/w40/ph.png" },
    { code: "PL", name: "Poland", dialCode: "+48", flag: "https://flagcdn.com/w40/pl.png" },
    { code: "PT", name: "Portugal", dialCode: "+351", flag: "https://flagcdn.com/w40/pt.png" },
    { code: "PR", name: "Puerto Rico", dialCode: "+1", flag: "https://flagcdn.com/w40/pr.png" },
    { code: "QA", name: "Qatar", dialCode: "+974", flag: "https://flagcdn.com/w40/qa.png" },
    { code: "RO", name: "Romania", dialCode: "+40", flag: "https://flagcdn.com/w40/ro.png" },
    { code: "RU", name: "Russia", dialCode: "+7", flag: "https://flagcdn.com/w40/ru.png" },
    { code: "RW", name: "Rwanda", dialCode: "+250", flag: "https://flagcdn.com/w40/rw.png" },
    { code: "WS", name: "Samoa", dialCode: "+685", flag: "https://flagcdn.com/w40/ws.png" },
    { code: "SM", name: "San Marino", dialCode: "+378", flag: "https://flagcdn.com/w40/sm.png" },
    { code: "ST", name: "São Tomé and Príncipe", dialCode: "+239", flag: "https://flagcdn.com/w40/st.png" },
    { code: "SA", name: "Saudi Arabia", dialCode: "+966", flag: "https://flagcdn.com/w40/sa.png" },
    { code: "SN", name: "Senegal", dialCode: "+221", flag: "https://flagcdn.com/w40/sn.png" },
    { code: "RS", name: "Serbia", dialCode: "+381", flag: "https://flagcdn.com/w40/rs.png" },
    { code: "SC", name: "Seychelles", dialCode: "+248", flag: "https://flagcdn.com/w40/sc.png" },
    { code: "SL", name: "Sierra Leone", dialCode: "+232", flag: "https://flagcdn.com/w40/sl.png" },
    { code: "SG", name: "Singapore", dialCode: "+65", flag: "https://flagcdn.com/w40/sg.png" },
    { code: "SK", name: "Slovakia", dialCode: "+421", flag: "https://flagcdn.com/w40/sk.png" },
    { code: "SI", name: "Slovenia", dialCode: "+386", flag: "https://flagcdn.com/w40/si.png" },
    { code: "SB", name: "Solomon Islands", dialCode: "+677", flag: "https://flagcdn.com/w40/sb.png" },
    { code: "SO", name: "Somalia", dialCode: "+252", flag: "https://flagcdn.com/w40/so.png" },
    { code: "ZA", name: "South Africa", dialCode: "+27", flag: "https://flagcdn.com/w40/za.png" },
    { code: "SS", name: "South Sudan", dialCode: "+211", flag: "https://flagcdn.com/w40/ss.png" },
    { code: "ES", name: "Spain", dialCode: "+34", flag: "https://flagcdn.com/w40/es.png" },
    { code: "LK", name: "Sri Lanka", dialCode: "+94", flag: "https://flagcdn.com/w40/lk.png" },
    { code: "SD", name: "Sudan", dialCode: "+249", flag: "https://flagcdn.com/w40/sd.png" },
    { code: "SR", name: "Suriname", dialCode: "+597", flag: "https://flagcdn.com/w40/sr.png" },
    { code: "SZ", name: "Eswatini", dialCode: "+268", flag: "https://flagcdn.com/w40/sz.png" },
    { code: "SE", name: "Sweden", dialCode: "+46", flag: "https://flagcdn.com/w40/se.png" },
    { code: "CH", name: "Switzerland", dialCode: "+41", flag: "https://flagcdn.com/w40/ch.png" },
    { code: "SY", name: "Syria", dialCode: "+963", flag: "https://flagcdn.com/w40/sy.png" },
    { code: "TW", name: "Taiwan", dialCode: "+886", flag: "https://flagcdn.com/w40/tw.png" },
    { code: "TJ", name: "Tajikistan", dialCode: "+992", flag: "https://flagcdn.com/w40/tj.png" },
    { code: "TZ", name: "Tanzania", dialCode: "+255", flag: "https://flagcdn.com/w40/tz.png" },
    { code: "TH", name: "Thailand", dialCode: "+66", flag: "https://flagcdn.com/w40/th.png" },
    { code: "TL", name: "Timor-Leste", dialCode: "+670", flag: "https://flagcdn.com/w40/tl.png" },
    { code: "TG", name: "Togo", dialCode: "+228", flag: "https://flagcdn.com/w40/tg.png" },
    { code: "TO", name: "Tonga", dialCode: "+676", flag: "https://flagcdn.com/w40/to.png" },
    { code: "TT", name: "Trinidad and Tobago", dialCode: "+1868", flag: "https://flagcdn.com/w40/tt.png" },
    { code: "TN", name: "Tunisia", dialCode: "+216", flag: "https://flagcdn.com/w40/tn.png" },
    { code: "TR", name: "Turkey", dialCode: "+90", flag: "https://flagcdn.com/w40/tr.png" },
    { code: "TM", name: "Turkmenistan", dialCode: "+993", flag: "https://flagcdn.com/w40/tm.png" },
    { code: "TV", name: "Tuvalu", dialCode: "+688", flag: "https://flagcdn.com/w40/tv.png" },
    { code: "UG", name: "Uganda", dialCode: "+256", flag: "https://flagcdn.com/w40/ug.png" },
    { code: "UA", name: "Ukraine", dialCode: "+380", flag: "https://flagcdn.com/w40/ua.png" },
    { code: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "https://flagcdn.com/w40/ae.png" },
    { code: "GB", name: "United Kingdom", dialCode: "+44", flag: "https://flagcdn.com/w40/gb.png" },
    { code: "US", name: "United States", dialCode: "+1", flag: "https://flagcdn.com/w40/us.png" },
    { code: "UY", name: "Uruguay", dialCode: "+598", flag: "https://flagcdn.com/w40/uy.png" },
    { code: "UZ", name: "Uzbekistan", dialCode: "+998", flag: "https://flagcdn.com/w40/uz.png" },
    { code: "VU", name: "Vanuatu", dialCode: "+678", flag: "https://flagcdn.com/w40/vu.png" },
    { code: "VA", name: "Vatican City", dialCode: "+39", flag: "https://flagcdn.com/w40/va.png" },
    { code: "VE", name: "Venezuela", dialCode: "+58", flag: "https://flagcdn.com/w40/ve.png" },
    { code: "VN", name: "Vietnam", dialCode: "+84", flag: "https://flagcdn.com/w40/vn.png" },
    { code: "YE", name: "Yemen", dialCode: "+967", flag: "https://flagcdn.com/w40/ye.png" },
    { code: "ZM", name: "Zambia", dialCode: "+260", flag: "https://flagcdn.com/w40/zm.png" },
    { code: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "https://flagcdn.com/w40/zw.png" },
]
